"""Code projects: a running interface, its repository, and its check.

A model builds into geometry and a board into a netlist. A code project
is already built - its dev server is running somewhere - so what there is
to store is where it lives: the checkout, the command that serves it, the
address it answers on and the command whose exit code says it still
works. Everything else is read from git and from the page itself when it
is asked for.

Three platforms share this: web, embedded and mobile. They are the same
loop over different things on screen, so they are one collection with a
field rather than three.

Git is asked with plain subprocess calls and short timeouts. A diff is
text and can be large, so what leaves here is parsed into files and hunks
and cut to a size a page can hold; a frozen one goes to GridFS through
``store.put_artifact`` like any other generated file.
"""

from __future__ import annotations

import asyncio
import os
import re
import signal
import subprocess
import time
import urllib.error
import urllib.request
from pathlib import Path

from . import compute, store

APPS = "apps"
PLATFORMS = ("web", "embedded", "mobile")
# What the tree shows after the name. It is what says which room a file
# opens, the way .3d and .pcb do.
EXT = {"web": ".web", "embedded": ".fw", "mobile": ".mobile"}

ROOT = Path(__file__).resolve().parent.parent
# What a dirty file said when a note was drawn, by blob hash. Kept here and
# not in the project's own .git: that checkout is somebody's working tree,
# and writing objects into it is not this room's business.
BLOBS = ROOT / ".cache" / "blobs"
BLOB_MAX = 2_000_000

# A test suite is allowed ten minutes. Longer than that and it is not a
# check somebody waits for between two edits.
TEST_TIMEOUT = 600
# What is kept of a test run's output, from the end - the summary and the
# failures are there, and the database is a hundred kilobytes a second away.
TAIL_CHARS = 16_000

# A page cannot usefully show more of a diff than this, and a lockfile
# regenerated by accident is tens of thousands of lines.
MAX_FILE_LINES = 600
MAX_TOTAL_LINES = 4000


# ---------------- git ----------------
def git(repo: str | Path, *args: str, timeout: float = 20) -> str:
    """One git command in `repo`, its output as text. Raises on failure."""
    out = subprocess.run(["git", "-C", str(repo), *args], capture_output=True,
                         timeout=timeout)
    if out.returncode != 0:
        raise RuntimeError(out.stderr.decode(errors="replace").strip()
                           or f"git {args[0]} failed")
    return out.stdout.decode(errors="replace")


def head(repo: str | Path) -> str:
    return git(repo, "rev-parse", "HEAD").strip()


def branch(repo: str | Path) -> str:
    return git(repo, "rev-parse", "--abbrev-ref", "HEAD").strip()


def dirty(repo: str | Path) -> dict[str, str]:
    """Every file that differs from HEAD, with the blob it would hash to.

    The hash is what a note remembers. Somebody else may be working in the
    same checkout - here, another agent is - and their uncommitted files
    were already dirty when the note was drawn. A file belongs to the note
    only if its content has moved since.
    """
    raw = git(repo, "status", "--porcelain", "-z", "--untracked-files=all")
    paths: list[str] = []
    entries = raw.split("\0")
    i = 0
    while i < len(entries):
        e = entries[i]
        i += 1
        if len(e) < 4:
            continue
        code, path = e[:2], e[3:]
        # A rename is two entries: the new name, then the old one.
        if code[0] in "RC":
            i += 1
        paths.append(path)
    out: dict[str, str] = {}
    present = [p for p in paths if (Path(repo) / p).is_file()]
    for p in paths:
        if p not in present:
            out[p] = "deleted"
    if present:
        hashes = git(repo, "hash-object", "--", *present).split()
        out.update(zip(present, hashes))
    return out


def blob_sha(data: bytes) -> str:
    """The id git gives a file's content, without asking git."""
    import hashlib
    return hashlib.sha1(b"blob %d\0" % len(data) + data).hexdigest()


def snapshot(repo: str | Path, state: dict[str, str]) -> int:
    """Keep what each dirty file says now, so a note drawn over somebody
    else's half-finished file can later be diffed against that file as it
    was, rather than against the last commit. Returns how many were kept."""
    BLOBS.mkdir(parents=True, exist_ok=True)
    kept = 0
    for path, sha in state.items():
        if sha == "deleted" or not re.fullmatch(r"[0-9a-f]{40,64}", sha):
            continue
        dst = BLOBS / sha
        if dst.exists():
            kept += 1
            continue
        src = Path(repo) / path
        try:
            if src.stat().st_size > BLOB_MAX:
                continue
            data = src.read_bytes()
            # Only under the hash it really has: the file may have moved
            # between git hashing it and this reading it.
            if blob_sha(data) != sha:
                continue
            tmp = dst.with_suffix(".part")
            tmp.write_bytes(data)
            tmp.replace(dst)
            kept += 1
        except OSError:
            pass
    return kept


def changed_since(repo: str | Path, base: str,
                  dirty_then: dict[str, str]) -> list[str]:
    """The files a note's work touched: committed since its base, or
    different from how they were when it was drawn."""
    now = dirty(repo)
    paths = set(git(repo, "diff", "--name-only", f"{base}..HEAD").split("\n"))
    for p, h in now.items():
        if dirty_then.get(p) != h:
            paths.add(p)
    return sorted(p for p in paths if p)


def patch(repo: str | Path, base: str, paths: list[str],
          then: dict[str, str] | None = None) -> str:
    """A unified diff of `paths` from how they were to the working tree.

    How they were is the base commit, except for a file that was already
    dirty when the note was drawn: that one is diffed from the copy kept
    at the time, so the note's diff is the note's work and not somebody
    else's half-finished edit. `git diff` leaves untracked files out, and
    a new component is exactly the kind of file a note produces, so those
    are diffed against nothing.
    """
    if not paths:
        return ""
    then = then or {}
    from_copy = [p for p in paths
                 if then.get(p, "deleted") != "deleted" and (BLOBS / then[p]).exists()]
    rest = [p for p in paths if p not in from_copy]
    text = ""
    tracked: set[str] = set()
    if rest:
        tracked = set(git(repo, "ls-files", "--", *rest).split("\n")) - {""}
        tracked |= set(git(repo, "ls-tree", "-r", "--name-only", base, "--",
                           *rest).split("\n")) - {""}
    if tracked:
        text += git(repo, "diff", "--no-color", "-U3", base, "--",
                    *sorted(tracked))
    for p in paths:
        if p in tracked:
            continue
        old = str(BLOBS / then[p]) if p in from_copy else "/dev/null"
        new = p if (Path(repo) / p).is_file() else "/dev/null"
        if old == "/dev/null" and new == "/dev/null":
            continue
        text += _no_index(repo, old, new, p)
    return text


def _no_index(repo: str | Path, old: str, new: str, path: str) -> str:
    """Two files diffed outside git's index, labelled as `path` - the kept
    copy's own name is a hash, which says nothing to whoever reads it."""
    # --no-index exits 1 when the files differ, which they always do here.
    out = subprocess.run(["git", "-C", str(repo), "diff", "--no-color",
                          "--no-index", "--", old, new],
                         capture_output=True, timeout=20)
    text = out.stdout.decode(errors="replace")
    if not text:
        return ""
    lines = text.split("\n")
    for i, line in enumerate(lines[:6]):
        if line.startswith("diff --git "):
            lines[i] = f"diff --git a/{path} b/{path}"
        elif line.startswith("--- ") and old != "/dev/null":
            lines[i] = f"--- a/{path}"
        elif line.startswith("+++ ") and new != "/dev/null":
            lines[i] = f"+++ b/{path}"
    return "\n".join(lines)


HUNK = re.compile(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@(.*)$")


def parse(text: str) -> dict:
    """A unified diff as files and hunks, cut to what a page can hold.

    Each line is `[kind, old_no, new_no, text]` with kind one of ' ', '+',
    '-', so the page draws both gutters without doing arithmetic.
    """
    files: list[dict] = []
    cur: dict | None = None
    hunk: dict | None = None
    old = new = 0
    total = 0
    cut = False
    for line in text.split("\n"):
        if line.startswith("diff --git "):
            m = re.match(r"diff --git a/(.*?) b/(.*)$", line)
            cur = {"path": m.group(2) if m else line[11:], "status": "modified",
                   "added": 0, "removed": 0, "hunks": [], "cut": False,
                   "binary": False}
            files.append(cur)
            hunk = None
            continue
        if cur is None:
            continue
        if line.startswith("new file"):
            cur["status"] = "added"
        elif line.startswith("deleted file"):
            cur["status"] = "deleted"
        elif line.startswith("rename to "):
            cur["status"] = "renamed"
            cur["path"] = line[10:]
        elif line.startswith("Binary files"):
            cur["binary"] = True
        elif line.startswith("+++ ") and hunk is None:
            name = line[4:]
            if name.startswith("b/"):
                cur["path"] = name[2:]
        elif line.startswith("--- ") and hunk is None:
            pass
        elif (m := HUNK.match(line)):
            old, new = int(m.group(1)), int(m.group(3))
            hunk = {"head": line, "lines": []}
            cur["hunks"].append(hunk)
        elif hunk is not None and line[:1] in (" ", "+", "-", "\\"):
            kind = line[:1]
            if kind == "+":
                cur["added"] += 1
            elif kind == "-":
                cur["removed"] += 1
            if kind == "\\":
                continue
            shown = sum(len(h["lines"]) for h in cur["hunks"])
            if shown >= MAX_FILE_LINES or total >= MAX_TOTAL_LINES:
                cur["cut"] = True
                cut = True
            else:
                hunk["lines"].append([
                    kind, old if kind != "+" else None,
                    new if kind != "-" else None, line[1:]])
                total += 1
            if kind != "+":
                old += 1
            if kind != "-":
                new += 1
    return {"files": files, "cut": cut,
            "added": sum(f["added"] for f in files),
            "removed": sum(f["removed"] for f in files)}


# ---------------- the dev server ----------------
def answers(url: str, timeout: float = 1.5) -> bool:
    """Whether something is serving at `url`. Any HTTP answer counts - a
    404 on the root is still a server that is up."""
    try:
        with urllib.request.urlopen(url, timeout=timeout):
            return True
    except urllib.error.HTTPError:
        return True
    except (urllib.error.URLError, OSError, ValueError):
        return False


def serve(app: dict) -> dict:
    """Start the project's dev server in its tab's container, unless
    something already answers.

    Left running, detached, under a name of its own: a dev server is slow
    to come up and is meant to outlive the request that asked for it. The
    host's network, so it answers on the host's loopback like any other.
    What it prints is read back with `docker logs` for the server tab.
    """
    from . import sandbox

    url = app.get("url") or ""
    probe = url.replace("10.0.2.2", "127.0.0.1")    # the phone's name for the host
    if probe and answers(probe):
        return {"started": False, "up": True, "why": "already answering"}
    if not app.get("dev"):
        return {"started": False, "up": False, "why": "no dev command"}
    platform = app.get("platform") or "web"
    if not sandbox.have_image(platform):
        raise sandbox.NoImage(f"the {platform} image is not built: "
                              f"{sandbox.build_hint(platform)}")
    name = server_name(app["_id"])
    subprocess.run(["docker", "rm", "-f", name], capture_output=True)
    cmd = sandbox.argv(platform, ["bash", "-c", app["dev"]], repo=app["repo"],
                       workdir=workdir(app), name=name)
    cmd.remove("--rm")
    cmd.insert(2, "-d")
    out = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    if out.returncode != 0:
        raise RuntimeError(out.stderr.strip()[-400:] or "docker run failed")
    return {"started": True, "up": False, "container": name}


def server_name(app_id: str) -> str:
    return f"redline-serve-{app_id}"


def server_log(app_id: str, limit: int = 200) -> list[str]:
    """What the dev server printed, from its container."""
    try:
        out = subprocess.run(["docker", "logs", "--tail", str(limit),
                              server_name(app_id)],
                             capture_output=True, text=True, timeout=10)
    except (OSError, subprocess.TimeoutExpired):
        return []
    return (out.stdout + out.stderr).splitlines()[-limit:]


def workdir(app: dict) -> str:
    return str(Path(app["repo"]) / (app.get("cwd") or ""))


# ---------------- the check ----------------
SUMMARY = re.compile(r"(\d+) (passed|failed|errors?|skipped|xfailed|xpassed)")


def counts(output: str) -> dict:
    """pytest, jest and vitest all end on a line of counts. Read the last
    one that has any; the exit code stays the verdict either way."""
    found: dict[str, int] = {}
    for line in reversed(output.splitlines()[-40:]):
        hits = SUMMARY.findall(line)
        if hits:
            for n, what in hits:
                key = "errors" if what.startswith("error") else what
                found[key] = found.get(key, 0) + int(n)
            break
    return found


async def run_test(db, app: dict) -> dict:
    """Run the project's test command in its tab's container, measured.

    The verdict is the exit code. The counts are read off the output for
    the pane's heading, and are only as good as the runner's own summary.
    """
    from . import sandbox

    if not app.get("test"):
        raise ValueError(f"{app['_id']}: no test command")
    platform = app.get("platform") or "web"
    started = store.now()
    t0 = time.monotonic()
    rc, output, job = await sandbox.run(
        platform, ["bash", "-c", app["test"]], repo=app["repo"],
        workdir=workdir(app), timeout=TEST_TIMEOUT,
        # The ceiling tools/capped.sh puts on a build on the host.
        extra=["--memory", "8g"])
    try:
        await compute.record(db, "test", await compute.current_revision(
            db, platform), model=app["_id"], rc=rc, **job)
    except Exception:                                # noqa: BLE001
        pass
    try:
        sha = head(app["repo"])
        state = dirty(app["repo"])
    except (RuntimeError, OSError, subprocess.TimeoutExpired):
        sha, state = None, {}
    result = {
        "at": started, "ok": rc == 0, "rc": rc,
        "wall_s": round(time.monotonic() - t0, 2),
        "cpu_s": job.get("cpu_s"), "counts": counts(output),
        "command": app["test"], "image": sandbox.image_of(platform),
        # What the tree looked like when it passed, so "the tests pass" can
        # be checked against the tree as it is now rather than taken on
        # trust from an older run.
        "head": sha, "tree": _digest(state),
        "tail": output[-TAIL_CHARS:], "lines": output.count("\n"),
    }
    await db[APPS].update_one({"_id": app["_id"]},
                              {"$set": {"last_test": result}})
    return result


def _digest(state: dict[str, str]) -> str:
    import hashlib
    return hashlib.sha1("\n".join(f"{k} {v}" for k, v in
                                  sorted(state.items())).encode()).hexdigest()


def tree_digest(repo: str | Path) -> str:
    return _digest(dirty(repo))


# ---------------- the catalog ----------------
def entry(a: dict) -> dict:
    """How a project shows in the tree."""
    platform = a.get("platform") or "web"
    return {"id": a["_id"], "title": a.get("title") or a["_id"],
            "platform": platform, "ext": EXT.get(platform, ".web"),
            "kind": "app"}


SAFE_ID = re.compile(r"^[A-Za-z0-9_-]+$")


def clean(body: dict) -> dict:
    """What may be written for a project, checked."""
    platform = body.get("platform") or "web"
    if platform not in PLATFORMS:
        raise ValueError("platform: " + " | ".join(PLATFORMS))
    repo = Path(body.get("repo") or "")
    if not repo.is_absolute() or not (repo / ".git").exists():
        raise ValueError(f"repo must be the absolute path of a git checkout: {repo}")
    return {k: body.get(k) for k in
            ("title", "folder", "cwd", "url", "dev", "test", "routes",
             "build", "elf", "device", "package", "activity", "target",
             "flash")
            if body.get(k) is not None} | {"platform": platform,
                                           "repo": str(repo)}
