"""Code projects: a running interface, its repository, and its check.

A model builds into geometry and a board into a netlist. A code project
is already built - its dev server is running somewhere - so what there is
to store is where it lives: the checkout, the command that serves it, the
address it answers on and the command whose exit code says it still
works. Everything else is read from git and from the page itself when it
is asked for.

Three platforms share this: web, embedded and mobile. They are the same
loop over different things on screen, so they are one collection with a
field rather than three.

Git is asked with plain subprocess calls and short timeouts. A diff is
text and can be large, so what leaves here is parsed into files and hunks
and cut to a size a page can hold; a frozen one goes to GridFS through
``store.put_artifact`` like any other generated file.
"""

from __future__ import annotations

import asyncio
import os
import re
import signal
import subprocess
import time
import urllib.error
import urllib.request
from pathlib import Path

from . import compute, store

APPS = "apps"
PLATFORMS = ("web", "embedded", "mobile")
# What the tree shows after the name. It is what says which room a file
# opens, the way .3d and .pcb do.
EXT = {"web": ".web", "embedded": ".fw", "mobile": ".mobile"}

ROOT = Path(__file__).resolve().parent.parent
LOGS = ROOT / ".cache" / "apps"

# A test suite is allowed ten minutes. Longer than that and it is not a
# check somebody waits for between two edits.
TEST_TIMEOUT = 600
# What is kept of a test run's output, from the end - the summary and the
# failures are there, and the database is a hundred kilobytes a second away.
TAIL_CHARS = 16_000

# A page cannot usefully show more of a diff than this, and a lockfile
# regenerated by accident is tens of thousands of lines.
MAX_FILE_LINES = 600
MAX_TOTAL_LINES = 4000


# ---------------- git ----------------
def git(repo: str | Path, *args: str, timeout: float = 20) -> str:
    """One git command in `repo`, its output as text. Raises on failure."""
    out = subprocess.run(["git", "-C", str(repo), *args], capture_output=True,
                         timeout=timeout)
    if out.returncode != 0:
        raise RuntimeError(out.stderr.decode(errors="replace").strip()
                           or f"git {args[0]} failed")
    return out.stdout.decode(errors="replace")


def head(repo: str | Path) -> str:
    return git(repo, "rev-parse", "HEAD").strip()


def branch(repo: str | Path) -> str:
    return git(repo, "rev-parse", "--abbrev-ref", "HEAD").strip()


def dirty(repo: str | Path) -> dict[str, str]:
    """Every file that differs from HEAD, with the blob it would hash to.

    The hash is what a note remembers. Somebody else may be working in the
    same checkout - here, another agent is - and their uncommitted files
    were already dirty when the note was drawn. A file belongs to the note
    only if its content has moved since.
    """
    raw = git(repo, "status", "--porcelain", "-z", "--untracked-files=all")
    paths: list[str] = []
    entries = raw.split("\0")
    i = 0
    while i < len(entries):
        e = entries[i]
        i += 1
        if len(e) < 4:
            continue
        code, path = e[:2], e[3:]
        # A rename is two entries: the new name, then the old one.
        if code[0] in "RC":
            i += 1
        paths.append(path)
    out: dict[str, str] = {}
    present = [p for p in paths if (Path(repo) / p).is_file()]
    for p in paths:
        if p not in present:
            out[p] = "deleted"
    if present:
        hashes = git(repo, "hash-object", "--", *present).split()
        out.update(zip(present, hashes))
    return out


def changed_since(repo: str | Path, base: str,
                  dirty_then: dict[str, str]) -> list[str]:
    """The files a note's work touched: committed since its base, or
    different from how they were when it was drawn."""
    now = dirty(repo)
    paths = set(git(repo, "diff", "--name-only", f"{base}..HEAD").split("\n"))
    for p, h in now.items():
        if dirty_then.get(p) != h:
            paths.add(p)
    return sorted(p for p in paths if p)


def patch(repo: str | Path, base: str, paths: list[str]) -> str:
    """A unified diff of `paths` from `base` to the working tree.

    `git diff` leaves untracked files out, and a new component is exactly
    the kind of file a note produces, so those are diffed against nothing.
    """
    if not paths:
        return ""
    tracked = set(git(repo, "ls-files", "--", *paths).split("\n")) - {""}
    tracked |= set(git(repo, "ls-tree", "-r", "--name-only", base, "--",
                       *paths).split("\n")) - {""}
    text = ""
    if tracked:
        text += git(repo, "diff", "--no-color", "-U3", base, "--",
                    *sorted(tracked))
    for p in paths:
        if p in tracked or not (Path(repo) / p).is_file():
            continue
        # --no-index exits 1 when the files differ, which they always do.
        out = subprocess.run(["git", "-C", str(repo), "diff", "--no-color",
                              "--no-index", "--", "/dev/null", p],
                             capture_output=True, timeout=20)
        text += out.stdout.decode(errors="replace")
    return text


HUNK = re.compile(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@(.*)$")


def parse(text: str) -> dict:
    """A unified diff as files and hunks, cut to what a page can hold.

    Each line is `[kind, old_no, new_no, text]` with kind one of ' ', '+',
    '-', so the page draws both gutters without doing arithmetic.
    """
    files: list[dict] = []
    cur: dict | None = None
    hunk: dict | None = None
    old = new = 0
    total = 0
    cut = False
    for line in text.split("\n"):
        if line.startswith("diff --git "):
            m = re.match(r"diff --git a/(.*?) b/(.*)$", line)
            cur = {"path": m.group(2) if m else line[11:], "status": "modified",
                   "added": 0, "removed": 0, "hunks": [], "cut": False,
                   "binary": False}
            files.append(cur)
            hunk = None
            continue
        if cur is None:
            continue
        if line.startswith("new file"):
            cur["status"] = "added"
        elif line.startswith("deleted file"):
            cur["status"] = "deleted"
        elif line.startswith("rename to "):
            cur["status"] = "renamed"
            cur["path"] = line[10:]
        elif line.startswith("Binary files"):
            cur["binary"] = True
        elif line.startswith("+++ ") and hunk is None:
            name = line[4:]
            if name.startswith("b/"):
                cur["path"] = name[2:]
        elif line.startswith("--- ") and hunk is None:
            pass
        elif (m := HUNK.match(line)):
            old, new = int(m.group(1)), int(m.group(3))
            hunk = {"head": line, "lines": []}
            cur["hunks"].append(hunk)
        elif hunk is not None and line[:1] in (" ", "+", "-", "\\"):
            kind = line[:1]
            if kind == "+":
                cur["added"] += 1
            elif kind == "-":
                cur["removed"] += 1
            if kind == "\\":
                continue
            shown = sum(len(h["lines"]) for h in cur["hunks"])
            if shown >= MAX_FILE_LINES or total >= MAX_TOTAL_LINES:
                cur["cut"] = True
                cut = True
            else:
                hunk["lines"].append([
                    kind, old if kind != "+" else None,
                    new if kind != "-" else None, line[1:]])
                total += 1
            if kind != "+":
                old += 1
            if kind != "-":
                new += 1
    return {"files": files, "cut": cut,
            "added": sum(f["added"] for f in files),
            "removed": sum(f["removed"] for f in files)}


# ---------------- the dev server ----------------
def answers(url: str, timeout: float = 1.5) -> bool:
    """Whether something is serving at `url`. Any HTTP answer counts - a
    404 on the root is still a server that is up."""
    try:
        with urllib.request.urlopen(url, timeout=timeout):
            return True
    except urllib.error.HTTPError:
        return True
    except (urllib.error.URLError, OSError, ValueError):
        return False


def serve(app: dict) -> dict:
    """Start the project's dev server, unless something already answers.

    Started in a session of its own and left running: a dev server is
    slow to come up and is meant to outlive the request that asked for it.
    What it prints goes to a file the room's log tab reads.
    """
    url = app.get("url") or ""
    if url and answers(url):
        return {"started": False, "up": True, "why": "already answering"}
    if not app.get("dev"):
        return {"started": False, "up": False, "why": "no dev command"}
    LOGS.mkdir(parents=True, exist_ok=True)
    log = LOGS / f"{app['_id']}.log"
    out = open(log, "ab")
    proc = subprocess.Popen(["bash", "-c", app["dev"]], cwd=workdir(app),
                            stdout=out, stderr=subprocess.STDOUT,
                            stdin=subprocess.DEVNULL, start_new_session=True)
    return {"started": True, "up": False, "pid": proc.pid, "log": str(log)}


def stop_served(pid: int) -> bool:
    try:
        os.killpg(pid, signal.SIGTERM)
        return True
    except (ProcessLookupError, PermissionError):
        return False


def server_log(app_id: str, limit: int = 200) -> list[str]:
    log = LOGS / f"{app_id}.log"
    try:
        lines = log.read_text(errors="replace").splitlines()
    except OSError:
        return []
    return lines[-limit:]


def workdir(app: dict) -> str:
    return str(Path(app["repo"]) / (app.get("cwd") or ""))


# ---------------- the check ----------------
SUMMARY = re.compile(r"(\d+) (passed|failed|errors?|skipped|xfailed|xpassed)")


def counts(output: str) -> dict:
    """pytest, jest and vitest all end on a line of counts. Read the last
    one that has any; the exit code stays the verdict either way."""
    found: dict[str, int] = {}
    for line in reversed(output.splitlines()[-40:]):
        hits = SUMMARY.findall(line)
        if hits:
            for n, what in hits:
                key = "errors" if what.startswith("error") else what
                found[key] = found.get(key, 0) + int(n)
            break
    return found


async def run_test(db, app: dict) -> dict:
    """Run the project's test command, measured the way a build is.

    The verdict is the exit code. The counts are read off the output for
    the pane's heading, and are only as good as the runner's own summary.
    """
    if not app.get("test"):
        raise ValueError(f"{app['_id']}: no test command")
    capped = ROOT / "tools" / "capped.sh"
    argv = ["bash", "-c", app["test"]]
    if capped.exists():
        argv = [str(capped), *argv]
    started = store.now()
    t0 = time.monotonic()
    meter = compute.Meter()
    proc = await asyncio.create_subprocess_exec(
        *argv, cwd=workdir(app), stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.STDOUT, start_new_session=True)
    meter.watch(proc.pid)
    timed_out = False
    try:
        raw, _ = await asyncio.wait_for(proc.communicate(), TEST_TIMEOUT)
    except asyncio.TimeoutError:
        timed_out = True
        try:
            os.killpg(proc.pid, signal.SIGKILL)
        except ProcessLookupError:
            pass
        raw = b""
        await proc.wait()
    job = meter.stop()
    output = raw.decode(errors="replace")
    if timed_out:
        output += f"\n(stopped after {TEST_TIMEOUT}s)"
    rc = proc.returncode if not timed_out else -9
    try:
        await compute.record(db, "test", await compute.current_revision(db),
                             model=app["_id"], rc=rc, **job)
    except Exception:                                # noqa: BLE001
        pass
    try:
        sha = head(app["repo"])
        state = dirty(app["repo"])
    except (RuntimeError, OSError, subprocess.TimeoutExpired):
        sha, state = None, {}
    result = {
        "at": started, "ok": rc == 0, "rc": rc,
        "wall_s": round(time.monotonic() - t0, 2),
        "cpu_s": job.get("cpu_s"), "counts": counts(output),
        "command": app["test"],
        # What the tree looked like when it passed, so "the tests pass" can
        # be checked against the tree as it is now rather than taken on
        # trust from an older run.
        "head": sha, "tree": _digest(state),
        "tail": output[-TAIL_CHARS:], "lines": output.count("\n"),
    }
    await db[APPS].update_one({"_id": app["_id"]},
                              {"$set": {"last_test": result}})
    return result


def _digest(state: dict[str, str]) -> str:
    import hashlib
    return hashlib.sha1("\n".join(f"{k} {v}" for k, v in
                                  sorted(state.items())).encode()).hexdigest()


def tree_digest(repo: str | Path) -> str:
    return _digest(dirty(repo))


# ---------------- the catalog ----------------
def entry(a: dict) -> dict:
    """How a project shows in the tree."""
    platform = a.get("platform") or "web"
    return {"id": a["_id"], "title": a.get("title") or a["_id"],
            "platform": platform, "ext": EXT.get(platform, ".web"),
            "kind": "app"}


SAFE_ID = re.compile(r"^[A-Za-z0-9_-]+$")


def clean(body: dict) -> dict:
    """What may be written for a project, checked."""
    platform = body.get("platform") or "web"
    if platform not in PLATFORMS:
        raise ValueError("platform: " + " | ".join(PLATFORMS))
    repo = Path(body.get("repo") or "")
    if not repo.is_absolute() or not (repo / ".git").exists():
        raise ValueError(f"repo must be the absolute path of a git checkout: {repo}")
    return {k: body.get(k) for k in
            ("title", "folder", "cwd", "url", "dev", "test", "routes")
            if body.get(k) is not None} | {"platform": platform,
                                           "repo": str(repo)}
