"""Component result cache: a model another one imports is its saved result,
not a fresh run of its source - Fusion's idea of a referenced component.

A build runs `export_model.py` in a fresh process, and every model it
imports used to be executed from its source again: the lid, the button
caps, the light pipes, the base and the station each spent two minutes
re-running the enclosure before doing a few seconds of their own work.

What is kept (`<cache>/m/<key>/`), right after a model module has run as
someone's import:

    meta.json   its module-level names: plain data (numbers, strings,
                lists, dicts, tuples...) and build123d objects (shapes,
                locations, planes, vectors, colours) with their labels,
                colours and Compound children, encoded as a small object
                table; names bound to modules or to things importable from
                elsewhere (`from build123d import Box`) as references;
                which top-level `def`s and `class`es to define again; what
                it printed and what it set in os.environ.
    shapes.bin  every OCCT shape those names hold, one BinTools file (so
                sub-shapes shared between names stay shared, triangulation
                included).

The key is content-addressed: the module's own text, its name, the keys of
every model it imports (transitively; for a bare `import lid`, the model
the importer's project resolves it to - backend/modnames.py), the uploaded files and board STEPs
its text names, REDLINE_IMPORT_ONLY at the moment it is imported, and the
versions of Python, build123d, OCP, this file and backend/assembly.py
(whose component marks the kept shapes carry). A pinned component is
written into the build directory at its pinned source, so its key - and its
cache entry - is the pinned version's. Nothing has to be invalidated: a
change anywhere below gives a different key.

Using it: `install()` puts a finder in front of the import system for the
build directory's model modules. Importing one whose entry exists fills the
module from the entry, defines its top-level functions and classes again
from the real source (same file, same line numbers, globals = the module),
and hangs a module `__getattr__` on it: a name that could not be kept (a
lambda, an open file, an instance of a class the model defines...) runs the
real source on first access, in that module, so the answer is the same,
only later. A missing entry runs the real source as before and keeps the
result. While one process computes an entry, another waiting for the same
key blocks on a lock instead of computing it a second time.

Board STEPs: `build123d.import_step` is wrapped for the build, so a large
STEP (a board's `B.part`, an uploaded bracket) is parsed once per file
content and read back as BREP afterwards.

    REDLINE_BUILD_CACHE        the directory (default <repo>/.cache/build),
                               or "off" to build without it
    REDLINE_BUILD_CACHE_MAX    size to prune to, e.g. 4G (default)
    REDLINE_BUILD_CACHE_DEBUG  1: say what the cache did on stderr

Stdlib only at import time: the subprocess imports this before build123d.
"""

from __future__ import annotations

import ast
import base64
import enum
import fcntl
import hashlib
import importlib
import importlib.machinery
import importlib.util
import json
import os
import pathlib
import shutil
import sys
import time
import types
from pathlib import Path

# 2: shapes carry the component marks of backend/assembly.py (one node per
# component in the viewer's tree); entries from before do not have them.
FORMAT = 2
ENV_FLAG = "REDLINE_IMPORT_ONLY"
STEP_MIN = 256 * 1024             # smaller STEPs read faster than a cache lookup is worth
LOCK_WAIT = 1800.0                # seconds a process waits for another computing the same entry
REPO = Path(__file__).resolve().parent.parent
GENERATED_BOARD = "Generated by Redline; do not edit."


def directory() -> Path | None:
    """Where entries live, or None when the cache is off."""
    raw = os.environ.get("REDLINE_BUILD_CACHE", "").strip()
    if raw.lower() in ("off", "0", "no", "false"):
        return None
    return Path(raw) if raw else REPO / ".cache" / "build"


def default_parallel() -> int:
    """Link rebuilds at once when REDLINE_LINK_BUILDS does not say: one per
    ~10 GB of memory (the build ceiling, tools/capped.sh) and per four
    hardware threads, at most three. 32 GB and 16 threads: 3."""
    try:
        mem = os.sysconf("SC_PAGE_SIZE") * os.sysconf("SC_PHYS_PAGES") / 2**30
    except (ValueError, OSError, AttributeError):
        mem = 16
    cpus = os.cpu_count() or 4
    return max(1, min(3, int(mem // 10), cpus // 4))


def _debug(msg: str) -> None:
    if os.environ.get("REDLINE_BUILD_CACHE_DEBUG") == "1":
        print(f"[build cache] {msg}", file=sys.__stderr__, flush=True)


def _sha(data: bytes | str) -> str:
    if isinstance(data, str):
        data = data.encode()
    return hashlib.sha256(data).hexdigest()


def _file_sha(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


# ---------------------------------------------------------------- keys

def imported_names(source: str) -> list[str]:
    """The top-level modules a source imports - the same reading as
    backend/links.py `imported_names` (kept here so the build subprocess
    does not import the backend)."""
    try:
        tree = ast.parse(source or "")
    except SyntaxError:
        return []
    out = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            out += [a.name.split(".")[0] for a in node.names]
        elif isinstance(node, ast.ImportFrom) and not node.level and node.module:
            out.append(node.module.split(".")[0])
        elif (isinstance(node, ast.Call) and node.args
              and isinstance(node.args[0], ast.Constant) and isinstance(node.args[0].value, str)
              and ((isinstance(node.func, ast.Attribute) and node.func.attr == "import_module")
                   or (isinstance(node.func, ast.Name) and node.func.id == "__import__"))):
            out.append(node.args[0].value.split(".")[0])
    return list(dict.fromkeys(out))


_RUNTIME: str | None = None


def runtime() -> str:
    """What else a result depends on: this file and backend/assembly.py
    (the component marks on its shapes), Python, build123d, OCP."""
    global _RUNTIME
    if _RUNTIME is None:
        import importlib.metadata as md
        import platform
        # The interpreter's version, not sys.version: that also names the
        # compiler and the day it was built, which differ between the
        # API container and the host's .venv - so a build an agent ran
        # never used what a link rebuild had kept, and the other way
        # round, with the same Python, build123d and OCP on both.
        python = f"{platform.python_implementation()} {platform.python_version()}"
        parts = [str(FORMAT), python, _sha(Path(__file__).read_bytes())[:16]]
        # The marks a kept shape carries are made there (component grouping).
        marks = Path(__file__).with_name("assembly.py")
        if marks.exists():
            parts.append(_sha(marks.read_bytes())[:16])
        for dist in ("build123d", "cadquery-ocp", "cadquery_ocp", "cadquery-ocp-novtk",
                     "ocp-viewer-core", "numpy", "scipy"):
            try:
                parts.append(f"{dist}={md.version(dist)}")
            except Exception:                           # noqa: BLE001 - not installed under that name
                pass
        # Which files make up the geometry libraries, by their hashes: the
        # same version installed twice is the same library, a patched one is
        # not.
        for dist in ("build123d", "cadquery-ocp-novtk"):
            try:
                parts.append(f"{dist} files={_installed_files(md.distribution(dist))}")
            except Exception:                           # noqa: BLE001 - not installed under that name
                pass
        try:
            import OCP
            parts.append(f"OCP={getattr(OCP, '__version__', '?')}")
        except Exception:                               # noqa: BLE001
            pass
        _RUNTIME = _sha("|".join(parts))
    return _RUNTIME


def _installed_files(dist) -> str:
    """A digest of a distribution's own files as its RECORD lists them,
    without what the installer adds (pip and uv write different ones)."""
    rows = []
    for line in (dist.read_text("RECORD") or "").splitlines():
        path = line.split(",", 1)[0]
        if not line or "__pycache__" in path or ".dist-info/" in path:
            continue
        rows.append(line)
    return _sha("\n".join(sorted(rows)))[:16]


def module_keys(models_dir: Path, root: Path, resolve=None) -> dict[str, str]:
    """Every importable module in the build directory and its key: its text,
    its name, the files its text names, and the keys of the modules it
    imports - the modules those imports load for this importer (a bare
    `import lid` is iot-fan's lid in iot-fan and the 80 mm one's there:
    `resolve(importer, name)`, backend/modnames.py; by default the
    manifest of the directory). A module in an import cycle has none."""
    models_dir, root = Path(models_dir), Path(root)
    if resolve is None:
        from . import modnames
        resolve = modnames.resolver(models_dir)
    texts = {p.stem: p.read_text(errors="replace") for p in sorted(models_dir.glob("*.py"))
             if p.stem.isidentifier()}
    # Files a model can open by name: uploads in the build root, board STEPs.
    files = [p for p in root.iterdir() if p.is_file()] if root.is_dir() else []
    boards = root / "_boards"
    if boards.is_dir():
        files += [p for p in boards.iterdir() if p.is_file()]
    file_sha: dict[Path, str] = {}

    keys: dict[str, str | None] = {}
    visiting: set[str] = set()

    def key(name: str) -> str | None:
        if name in keys:
            return keys[name]
        if name in visiting:
            return None
        visiting.add(name)
        text = texts[name]
        deps = []
        ok = True
        try:
            loads = {resolve(name, n) for n in imported_names(text)}
        except ImportError:                 # several models by that name: the build stops
            loads, ok = set(), False
        for dep in sorted(n for n in loads if n in texts and n != name):
            k = key(dep)
            if k is None:
                ok = False
            deps.append((dep, k))
        named = []
        for p in files:
            if p.name in text:
                if p not in file_sha:
                    file_sha[p] = _file_sha(p)
                named.append((p.name, file_sha[p]))
        visiting.discard(name)
        keys[name] = _sha(json.dumps([runtime(), name, _sha(text), deps, sorted(named)])) if ok else None
        return keys[name]

    for n in texts:
        key(n)
    return {n: k for n, k in keys.items() if k}


def variant(key: str, flag: str | None) -> str:
    """The entry for a module imported with REDLINE_IMPORT_ONLY = `flag`:
    a part behaves differently on its own (STANDALONE) and imported."""
    return _sha(f"{key}|{ENV_FLAG}={flag!r}")


# ---------------------------------------------------------------- encoding

class Uncacheable(Exception):
    """A value the cache cannot keep faithfully."""


_FUNC = (types.FunctionType, types.BuiltinFunctionType, type)
_SKIP_DUNDER = {"__name__", "__file__", "__loader__", "__spec__", "__package__", "__builtins__",
                "__cached__", "__path__", "__getattr__", "__dir__"}
_KEEP_DUNDER = {"__doc__", "__all__", "__annotations__"}


def _resolve(module: str, qualname: str):
    obj = importlib.import_module(module)
    for part in qualname.split("."):
        obj = getattr(obj, part)
    return obj


class Encoder:
    """Values to JSON plus a list of OCCT shapes (written with BinTools).

    Scalars are themselves; anything else is a tagged dict. Lists, dicts,
    sets and build123d objects go into an object table and are referred to
    as {"o": i}, so a shape held by two names is one shape after loading,
    and the parent/children links of a Compound survive."""

    def __init__(self, model_modules: set[str], self_name: str = ""):
        self.model_modules = model_modules
        self.self_name = self_name
        self.objects: list = []
        self.memo: dict[int, int] = {}
        self.keep: list = []                 # alive, so no id() is reused meanwhile
        self.shapes: list = []
        self.shape_memo: dict[int, int] = {}
        self.vertex = None
        self.uses_models: set[str] = set()   # model modules the values refer to

    # -- helpers
    def _table(self, obj, make):
        i = self.memo.get(id(obj))
        if i is not None:
            return {"o": i}
        i = len(self.objects)
        self.objects.append(None)
        self.memo[id(obj)] = i
        self.keep.append(obj)
        self.objects[i] = make()
        return {"o": i}

    def mark(self) -> tuple[int, int]:
        return len(self.objects), len(self.shapes)

    def rollback(self, mark: tuple[int, int]) -> None:
        """Forget what a value that failed half way put in the tables."""
        n, m = mark
        del self.objects[n:]
        del self.shapes[m:]
        self.memo = {k: i for k, i in self.memo.items() if i < n}
        self.shape_memo = {k: i for k, i in self.shape_memo.items() if i < m}

    def _topo(self, s) -> int:
        i = self.shape_memo.get(id(s))
        if i is None:
            i = len(self.shapes)
            self.shapes.append(s)
            self.shape_memo[id(s)] = i
            self.keep.append(s)
        return i

    def _loc_index(self, loc) -> int:
        """A TopLoc_Location kept exactly: on a vertex, in the shape file."""
        if self.vertex is None:
            from OCP.BRepBuilderAPI import BRepBuilderAPI_MakeVertex
            from OCP.gp import gp_Pnt
            self.vertex = BRepBuilderAPI_MakeVertex(gp_Pnt(0, 0, 0)).Vertex()
        i = len(self.shapes)
        self.shapes.append(self.vertex.Located(loc))
        return i

    def class_ref(self, cls, models: bool = False) -> list[str]:
        """A class by where it is defined. `models`: another model's class
        will do (a NamedTuple: its instances are only their items)."""
        mod, qual = getattr(cls, "__module__", None), getattr(cls, "__qualname__", None)
        if not mod or not qual or "<" in qual:
            raise Uncacheable(f"{cls!r} has no importable name")
        if mod == self.self_name or (mod in self.model_modules and not models):
            raise Uncacheable(f"{qual} is defined by a model ({mod})")
        if mod in self.model_modules:
            self.uses_models.add(mod)
        try:
            if _resolve(mod, qual) is not cls:
                raise Uncacheable(f"{mod}.{qual} is not that class")
        except Uncacheable:
            raise
        except Exception as exc:                        # noqa: BLE001
            raise Uncacheable(f"{mod}.{qual}: {exc}") from exc
        return [mod, qual]

    def ref(self, obj) -> dict:
        """A function, class or other named thing, by where it is defined."""
        mod, qual = getattr(obj, "__module__", None), getattr(obj, "__qualname__", None)
        if not mod or not qual or "<" in qual:
            raise Uncacheable(f"{obj!r} has no importable name")
        if mod == self.self_name:
            raise Uncacheable(f"{qual} is defined here")
        if mod in self.model_modules:
            # Another model's function: that model resolves it on loading.
            if "." in qual:
                raise Uncacheable(f"{mod}.{qual} is not top-level")
            self.uses_models.add(mod)
            return {"ref": [mod, qual]}
        try:
            if _resolve(mod, qual) is not obj:
                raise Uncacheable(f"{mod}.{qual} is not the same object")
        except Uncacheable:
            raise
        except Exception as exc:                        # noqa: BLE001
            raise Uncacheable(f"{mod}.{qual}: {exc}") from exc
        return {"ref": [mod, qual]}

    # -- the walk
    def enc(self, v):
        t = type(v)
        if v is None or t in (bool, int, str, float):
            return v
        if t is tuple:
            return {"tuple": [self.enc(x) for x in v]}
        if t is list:
            return self._table(v, lambda: {"list": [self.enc(x) for x in v]})
        if t is dict:
            return self._table(v, lambda: {"dict": [[self.enc(k), self.enc(x)] for k, x in v.items()]})
        if t is set:
            return self._table(v, lambda: {"set": [self.enc(x) for x in v]})
        if t is frozenset:
            return {"frozenset": [self.enc(x) for x in v]}
        if t is bytes:
            return {"bytes": base64.b64encode(v).decode()}
        if t is complex:
            return {"complex": [v.real, v.imag]}
        if isinstance(v, types.ModuleType):
            if v.__name__ in self.model_modules:
                self.uses_models.add(v.__name__)
            if sys.modules.get(v.__name__) is not v:
                raise Uncacheable(f"module {v.__name__} is not the imported one")
            return {"module": v.__name__}
        if isinstance(v, enum.Enum):
            return {"enum": [self.class_ref(t), v.name]}
        if isinstance(v, pathlib.PurePath):
            return {"path": [self.class_ref(t), str(v)]}
        if isinstance(v, _FUNC):
            return self.ref(v)
        ocp = self._ocp(v, t)
        if ocp is not None:
            return ocp
        if isinstance(v, tuple):                        # a NamedTuple, a board's Hole...
            return {"ntuple": [self.class_ref(t, models=True), [self.enc(x) for x in v]]}
        mod = getattr(t, "__module__", "") or ""
        if mod == "build123d" or mod.startswith("build123d."):
            return self._b123d(v, t)
        raise Uncacheable(f"{t.__module__}.{t.__qualname__} is not kept")

    def _ocp(self, v, t):
        mod = getattr(t, "__module__", "") or ""
        if not mod.startswith("OCP"):
            return None
        from OCP.TopoDS import TopoDS_Shape
        if isinstance(v, TopoDS_Shape):
            return None if v.IsNull() else {"topo": self._topo(v)}
        name = t.__name__
        if name == "TopLoc_Location":
            return {"loc": self._loc_index(v)}
        if name == "gp_Trsf":
            from OCP.TopLoc import TopLoc_Location
            return {"trsf": self._loc_index(TopLoc_Location(v))}
        if name in ("gp_Vec", "gp_Pnt", "gp_Dir", "gp_XYZ"):
            return {name: [v.X(), v.Y(), v.Z()]}
        if name == "gp_Ax1":
            return {name: [self.enc(v.Location()), self.enc(v.Direction())]}
        if name in ("gp_Ax2", "gp_Ax3"):
            out = [self.enc(v.Location()), self.enc(v.Direction()), self.enc(v.XDirection())]
            if name == "gp_Ax3":
                out.append(bool(v.Direct()))
            return {name: out}
        if name == "gp_Pln":
            return {name: self.enc(v.Position())}
        if name in ("Quantity_ColorRGBA", "Quantity_Color"):
            from OCP.Quantity import Quantity_TOC_RGB
            rgb = v.GetRGB() if name == "Quantity_ColorRGBA" else v
            vals = list(rgb.Values(Quantity_TOC_RGB))
            if name == "Quantity_ColorRGBA":
                vals.append(v.Alpha())
            return {name: vals}
        if name == "gp_GTrsf":
            return {name: [v.Value(r, c) for r in (1, 2, 3) for c in (1, 2, 3, 4)]}
        if name == "Bnd_Box":
            if v.IsVoid():
                return {name: None}
            if v.IsOpen() or v.IsWhole():
                raise Uncacheable("an open Bnd_Box")
            # The corners come with the gap added; the box is kept as it is
            # stored (corners, gap) when that gives the same corners back.
            g = v.GetGap()
            lo, hi = v.CornerMin().Coord(), v.CornerMax().Coord()
            raw = [x + g for x in lo] + [x - g for x in hi]
            if g and all(r - g == x for r, x in zip(raw[:3], lo)) \
                    and all(r + g == x for r, x in zip(raw[3:], hi)):
                return {name: [*raw, g]}
            return {name: [*lo, *hi, 0.0]}
        if isinstance(v, enum.Enum) or hasattr(t, "__members__"):
            return {"enum": [self.class_ref(t), v.name]}
        raise Uncacheable(f"OCP {name} is not kept")

    def _b123d(self, v, t):
        from build123d.build_common import Builder
        from build123d.topology.shape_core import Shape
        cls = self.class_ref(t)
        is_shape, is_builder = isinstance(v, Shape), isinstance(v, Builder)

        def attrs():
            out = []
            for k, x in (getattr(v, "__dict__", None) or {}).items():
                if is_shape and k == "_history":
                    x = None              # how it was made, not what it is
                elif is_builder and (isinstance(x, (types.FrameType, types.GeneratorType))
                                     or type(x).__name__ == "_GeneratorContextManager"):
                    x = None              # a closed builder's link to the code that ran it
                out.append([k, self.enc(x)])
            return out

        if isinstance(v, list):
            return self._table(v, lambda: {"lsub": cls, "items": [self.enc(x) for x in v], "d": attrs()})
        if isinstance(v, dict):
            raise Uncacheable(f"{t.__qualname__}: a dict subclass")
        if isinstance(v, tuple):
            return {"ntuple": [cls, [self.enc(x) for x in v]]}
        if not hasattr(v, "__dict__"):
            raise Uncacheable(f"{t.__qualname__} has no __dict__")
        return self._table(v, lambda: {"obj": cls, "d": attrs()})

    def write_shapes(self, path: Path) -> None:
        from OCP.BinTools import BinTools
        from OCP.BRep import BRep_Builder
        from OCP.TopoDS import TopoDS_Compound
        comp = TopoDS_Compound()
        b = BRep_Builder()
        b.MakeCompound(comp)
        for s in self.shapes:
            b.Add(comp, s)
        # A write that failed half way (disk full, memory) is not an entry:
        # Store.write would rename it into place for every later build to
        # parse.
        if not BinTools.Write_s(comp, str(path)) or not Path(path).stat().st_size:
            raise OSError(f"BinTools could not write {path}")


class Decoder:
    def __init__(self, objects: list, shapes_path: Path | None):
        self.objects = objects
        self.done: dict[int, object] = {}
        self.shapes: list = []
        if shapes_path is not None and shapes_path.exists():
            from OCP.BinTools import BinTools
            from OCP.TopoDS import TopoDS_Iterator, TopoDS_Shape
            from build123d.topology.shape_core import downcast
            whole = TopoDS_Shape()
            # Read whole or not at all: a file pruned or cut short under us
            # is an unreadable entry (a miss), never a half-read shape.
            if not BinTools.Read_s(whole, str(shapes_path)) or whole.IsNull():
                raise ValueError(f"{shapes_path}: not a whole BinTools file")
            it = TopoDS_Iterator(whole)
            while it.More():
                self.shapes.append(downcast(it.Value()))
                it.Next()

    def dec(self, e):
        if e is None or type(e) in (bool, int, str, float):
            return e
        if "o" in e:
            return self.obj(e["o"])
        tag, val = next(iter(e.items()))
        if tag == "tuple":
            return tuple(self.dec(x) for x in val)
        if tag == "frozenset":
            return frozenset(self.dec(x) for x in val)
        if tag == "bytes":
            return base64.b64decode(val)
        if tag == "complex":
            return complex(*val)
        if tag == "module":
            return importlib.import_module(val)
        if tag == "ref":
            return _resolve(*val)
        if tag == "enum":
            return getattr(_resolve(*val[0]), val[1])
        if tag == "path":
            return _resolve(*val[0])(val[1])
        if tag == "ntuple":
            cls = _resolve(*val[0])
            items = [self.dec(x) for x in val[1]]
            return cls._make(items) if hasattr(cls, "_make") else tuple.__new__(cls, items)
        if tag == "topo":
            return self.shapes[val]
        if tag == "loc":
            return self.shapes[val].Location()
        if tag == "trsf":
            return self.shapes[val].Location().Transformation()
        from OCP import gp
        if tag in ("gp_Vec", "gp_Pnt", "gp_Dir", "gp_XYZ"):
            return getattr(gp, tag)(*val)
        if tag == "gp_Ax1":
            return gp.gp_Ax1(self.dec(val[0]), self.dec(val[1]))
        if tag == "gp_Ax2":
            return gp.gp_Ax2(self.dec(val[0]), self.dec(val[1]), self.dec(val[2]))
        if tag == "gp_Ax3":
            ax = gp.gp_Ax3(self.dec(val[0]), self.dec(val[1]), self.dec(val[2]))
            if not val[3]:
                ax.YReverse()
            return ax
        if tag == "gp_Pln":
            return gp.gp_Pln(self.dec(val))
        if tag in ("Quantity_ColorRGBA", "Quantity_Color"):
            from OCP.Quantity import Quantity_Color, Quantity_ColorRGBA, Quantity_TOC_RGB
            c = Quantity_Color(val[0], val[1], val[2], Quantity_TOC_RGB)
            return Quantity_ColorRGBA(c, val[3]) if tag == "Quantity_ColorRGBA" else c
        if tag == "Bnd_Box":
            from OCP.Bnd import Bnd_Box
            box = Bnd_Box()
            if val is not None:
                box.Update(*val[:6])
                if val[6]:
                    box.SetGap(val[6])
            return box
        if tag == "gp_GTrsf":
            g = gp.gp_GTrsf()
            for i, x in enumerate(val):
                g.SetValue(i // 4 + 1, i % 4 + 1, x)
            return g
        raise ValueError(f"unknown tag {tag}")

    def obj(self, i: int):
        if i in self.done:
            return self.done[i]
        e = self.objects[i]
        tag, val = next(iter(e.items()))
        if tag == "list":
            out = []
            self.done[i] = out
            out.extend(self.dec(x) for x in val)
        elif tag == "dict":
            out = {}
            self.done[i] = out
            for k, x in val:
                out[self.dec(k)] = self.dec(x)
        elif tag == "set":
            out = set()
            self.done[i] = out
            out.update(self.dec(x) for x in val)
        elif tag == "lsub":
            cls = _resolve(*val)
            out = cls.__new__(cls)
            self.done[i] = out
            list.extend(out, [self.dec(x) for x in e["items"]])
            for k, x in e["d"]:
                out.__dict__[k] = self.dec(x)
        elif tag == "obj":
            cls = _resolve(*val)
            out = cls.__new__(cls)
            self.done[i] = out
            for k, x in e["d"]:
                out.__dict__[k] = self.dec(x)
        else:
            raise ValueError(f"unknown object {tag}")
        return out


def encode_value(value, model_modules: set[str] = frozenset()) -> tuple[dict, Encoder]:
    """One value (an imported STEP, say) as an entry's meta and shapes."""
    enc = Encoder(set(model_modules))
    data = enc.enc(value)
    return {"value": data, "objects": enc.objects}, enc


# ---------------------------------------------------------------- the store

class Store:
    def __init__(self, root: Path):
        self.root = Path(root)

    def path(self, kind: str, key: str) -> Path:
        return self.root / kind / key[:2] / key

    def has(self, kind: str, key: str) -> bool:
        return (self.path(kind, key) / "meta.json").exists()

    def read(self, kind: str, key: str) -> tuple[dict, Path] | None:
        p = self.path(kind, key)
        try:
            meta = json.loads((p / "meta.json").read_text())
        except (OSError, ValueError):
            return None
        if meta.get("format") != FORMAT:
            return None
        try:
            os.utime(p / "meta.json")                   # recently used: pruned last
        except OSError:
            pass
        return meta, p / "shapes.bin"

    def write(self, kind: str, key: str, meta: dict, enc: Encoder) -> None:
        final = self.path(kind, key)
        if (final / "meta.json").exists():
            return
        final.parent.mkdir(parents=True, exist_ok=True)
        tmp = final.parent / f".{key}.{os.getpid()}.tmp"
        shutil.rmtree(tmp, ignore_errors=True)
        tmp.mkdir()
        try:
            if enc.shapes:
                enc.write_shapes(tmp / "shapes.bin")
            (tmp / "meta.json").write_text(json.dumps({"format": FORMAT, **meta}))
            try:
                os.rename(tmp, final)
            except OSError:                             # another process was first
                shutil.rmtree(tmp, ignore_errors=True)
        except BaseException:
            shutil.rmtree(tmp, ignore_errors=True)
            raise

    def lock(self, kind: str, key: str) -> "_Lock":
        return _Lock(self.root / "locks" / f"{kind}-{key}.lock")

    def prune(self, limit: int) -> int:
        """Least recently used entries out until the cache fits in `limit`
        bytes. Returns how many went."""
        entries = []
        total = 0
        for kind in ("m", "step"):
            for meta in (self.root / kind).glob("*/*/meta.json"):
                d = meta.parent
                try:
                    size = sum(f.stat().st_size for f in d.iterdir())
                    entries.append((meta.stat().st_mtime, size, d))
                except OSError:
                    continue
                total += size
        gone = 0
        for _at, size, d in sorted(entries):
            if total <= limit:
                break
            shutil.rmtree(d, ignore_errors=True)
            total -= size
            gone += 1
        return gone


class _Lock:
    """An exclusive lock between build processes: the second waits for the
    first to finish computing an entry instead of computing it too."""

    def __init__(self, path: Path):
        self.path = path
        self.fd = None

    def __enter__(self):
        try:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            self.fd = os.open(self.path, os.O_RDWR | os.O_CREAT, 0o644)
        except OSError:
            self.fd = None
            return self
        deadline = time.monotonic() + LOCK_WAIT
        while True:
            try:
                fcntl.flock(self.fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
                return self
            except BlockingIOError:
                if time.monotonic() > deadline:     # go ahead without it
                    os.close(self.fd)
                    self.fd = None
                    return self
                time.sleep(0.2)

    def __exit__(self, *exc):
        if self.fd is not None:
            try:
                fcntl.flock(self.fd, fcntl.LOCK_UN)
            finally:
                os.close(self.fd)
                self.fd = None


def _size(text: str) -> int:
    text = (text or "").strip().upper()
    mult = {"K": 2**10, "M": 2**20, "G": 2**30, "T": 2**40}
    try:
        if text and text[-1] in mult:
            return int(float(text[:-1]) * mult[text[-1]])
        return int(text)
    except ValueError:
        return 4 * 2**30


# ---------------------------------------------------------------- what a run printed

class _Tee:
    """sys.stdout/sys.stderr for the build: everything still goes out, and
    what a model prints while it runs is also kept with its entry."""

    def __init__(self, stream):
        self._stream = stream

    def write(self, s):
        if _CAPTURE and _CAPTURE[-1] is not None:
            _CAPTURE[-1].append(s)
        return self._stream.write(s)

    def flush(self):
        return self._stream.flush()

    def __getattr__(self, name):
        return getattr(self._stream, name)


_CAPTURE: list[list | None] = []
_REPLAYED: set[str] = set()


# ---------------------------------------------------------------- the finder

def _top_defs(tree: ast.Module) -> dict[str, list]:
    out: dict[str, list] = {}
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            out.setdefault(node.name, []).append(node)
    return out


def _names_in(node) -> set[str]:
    return {n.id for n in ast.walk(node) if isinstance(n, ast.Name)}


def _def_time_names(node) -> set[str]:
    """Names a def or class statement reads when it runs, outside the body
    it defines: defaults, decorators, annotations, bases."""
    parts = list(getattr(node, "decorator_list", []))
    if isinstance(node, ast.ClassDef):
        parts += [*node.bases, *[k.value for k in node.keywords]]
    else:
        a = node.args
        parts += [*a.defaults, *[d for d in a.kw_defaults if d is not None], node.returns]
        for arg in [*a.posonlyargs, *a.args, *a.kwonlyargs, a.vararg, a.kwarg]:
            if arg is not None and arg.annotation is not None:
                parts.append(arg.annotation)
    out: set[str] = set()
    for p in parts:
        if p is not None:
            out |= _names_in(p)
    return out


def _scope_globals(table) -> set[str]:
    out = {s.get_name() for s in table.get_symbols() if s.is_global()}
    for child in table.get_children():
        out |= _scope_globals(child)
    return out


def _reads(source: str, file: str | None, nodes: dict) -> dict[str, set[str]]:
    """The module-level names each top-level def/class reads - in its body
    (Python's own symbol tables: a parameter `b` is not the global `b`)
    and when the statement runs."""
    import symtable
    top = symtable.symtable(source, file or "<model>", "exec")
    tables: dict[tuple[str, int], object] = {}
    for child in top.get_children():
        tables[(child.get_name(), child.get_lineno())] = child
    out = {}
    for k, node in nodes.items():
        table = tables.get((k, node.lineno))
        body = _scope_globals(table) if table is not None else _names_in(node)
        out[k] = body | _def_time_names(node)
    return out


class Cache:
    """The cache as one build process uses it."""

    def __init__(self, models_dir: Path, root: Path, store: Store, target: str | None = None):
        self.models_dir = Path(models_dir)
        self.root = Path(root)
        self.store = store
        self.target = target
        self.keys: dict[str, str] = {}
        self.modules: set[str] = set()          # every model/board module name in the directory
        self.handled: set[str] = set()          # the ones the finder serves
        self.stats = {"hit": [], "miss": [], "unkept": {}, "fallback": [], "step_hit": 0, "step_miss": 0}

    # -- setting up
    def scan(self) -> None:
        self.keys = module_keys(self.models_dir, self.root)
        for p in self.models_dir.glob("*.py"):
            if not p.stem.isidentifier():
                continue
            self.modules.add(p.stem)
            text = p.read_text(errors="replace")
            if GENERATED_BOARD in text or "sys.modules[__name__]" in text:
                continue                        # a board module (fast, lazy) or an alias
            if p.stem == self.target or p.stem not in self.keys:
                continue
            self.handled.add(p.stem)

    # -- import machinery
    def find_spec(self, fullname, path=None, target=None):
        if path is not None or fullname not in self.handled or fullname in sys.modules:
            return None
        file = self.models_dir / f"{fullname}.py"
        if not file.exists():
            return None
        loader = _Loader(fullname, str(file), self)
        return importlib.util.spec_from_file_location(fullname, file, loader=loader)

    def invalidate_caches(self):
        pass

    # -- the work
    def entry_key(self, name: str, flag: str | None) -> str:
        return variant(self.keys[name], flag)

    def load(self, module, name: str, vkey: str, loader) -> bool:
        got = self.store.read("m", vkey)
        if not got:
            return False
        meta, shapes = got
        t = time.monotonic()
        try:
            _fill(module, meta, shapes, loader, self)
        except Exception as exc:                        # noqa: BLE001 - a bad entry is a miss
            _debug(f"{name}: entry unreadable ({type(exc).__name__}: {exc}); running it")
            shutil.rmtree(self.store.path("m", vkey), ignore_errors=True)
            for k in [k for k in module.__dict__ if k not in _SKIP_DUNDER]:
                module.__dict__.pop(k, None)
            module.__dict__.pop("__getattr__", None)
            return False
        self.stats["hit"].append([name, round(time.monotonic() - t, 2)])
        _debug(f"{name}: from the cache in {time.monotonic() - t:.2f}s")
        return True

    def save(self, module, name: str, vkey: str, out: list, env: dict, flag: str | None) -> None:
        t = time.monotonic()
        try:
            meta, enc, unkept = _snapshot(module, name, self.modules)
        except Exception as exc:                        # noqa: BLE001 - the build goes on
            reason = str(exc) if isinstance(exc, Uncacheable) else f"{type(exc).__name__}: {exc}"
            self.stats["unkept"][name] = reason
            _debug(f"{name}: not kept ({reason})")
            return
        meta.update({"module": name, "flag": flag, "env": env, "out": out,
                     "unkept": unkept, "at": time.time()})
        try:
            self.store.write("m", vkey, meta, enc)
        except Exception as exc:                        # noqa: BLE001 - a build never fails over this
            _debug(f"{name}: could not write entry ({type(exc).__name__}: {exc})")
            return
        _debug(f"{name}: kept in {time.monotonic() - t:.2f}s"
               + (f"; run on access: {', '.join(sorted(unkept))}" if unkept else ""))


class _Loader(importlib.machinery.SourceFileLoader):
    def __init__(self, fullname, path, cache: Cache):
        super().__init__(fullname, path)
        self.cache = cache
        self.flag: str | None = None

    def exec_module(self, module):
        cache, name = self.cache, module.__name__
        flag = self.flag = os.environ.get(ENV_FLAG)
        vkey = cache.entry_key(name, flag)
        # In whatever is running now, this import is a mark, not text: its
        # output is its own entry's.
        if _CAPTURE and _CAPTURE[-1] is not None:
            _CAPTURE[-1].append(["mod", name, vkey])
        _CAPTURE.append(None)
        try:
            if cache.load(module, name, vkey, self):
                return
            with cache.store.lock("m", vkey):
                if cache.load(module, name, vkey, self):
                    return
                self._run_and_keep(module, name, vkey, flag)
        finally:
            _CAPTURE.pop()

    def _run_and_keep(self, module, name, vkey, flag):
        cache = self.cache
        env0 = dict(os.environ)
        files0 = _files(cache.root)
        out: list = []
        _CAPTURE[-1] = out
        t = time.monotonic()
        super().exec_module(module)                     # the model's own source, as always
        _CAPTURE[-1] = None
        cache.stats["miss"].append([name, round(time.monotonic() - t, 1)])
        _REPLAYED.add(name)
        if _files(cache.root) != files0:
            cache.stats["unkept"][name] = "it wrote files"
            _debug(f"{name}: not kept (it wrote files while imported)")
            return
        env1 = dict(os.environ)
        env = {k: env1.get(k) for k in set(env0) | set(env1) if env0.get(k) != env1.get(k)}
        cache.save(module, name, vkey, _merge(out), env, flag)

    def run_source(self, module):
        """The real source, in this module, after all: a name the entry could
        not keep was asked for."""
        flag = self.flag
        before = os.environ.get(ENV_FLAG)
        _set_env(ENV_FLAG, flag)
        self.cache.stats["fallback"].append(module.__name__)
        _debug(f"{module.__name__}: running its source for a name the cache does not keep")
        try:
            super().exec_module(module)
        finally:
            _set_env(ENV_FLAG, before)


def _set_env(k, v):
    if v is None:
        os.environ.pop(k, None)
    else:
        os.environ[k] = v


def _merge(out: list) -> list:
    merged: list = []
    for item in out:
        if isinstance(item, str) and merged and isinstance(merged[-1], str):
            merged[-1] += item
        else:
            merged.append(item)
    return merged


def _files(root: Path) -> dict:
    """What a module could have written: the build root without the model
    sources and the viewer's output."""
    out = {}
    for dirpath, dirnames, filenames in os.walk(root):
        if Path(dirpath) == root:
            dirnames[:] = [d for d in dirnames if d not in ("models", "assets")]
        dirnames[:] = [d for d in dirnames if d != "__pycache__"]
        for f in filenames:
            p = os.path.join(dirpath, f)
            try:
                st = os.stat(p)
                out[p] = (st.st_size, st.st_mtime_ns)
            except OSError:
                pass
    return out


def _snapshot(module, name: str, model_modules: set[str]) -> tuple[dict, Encoder, list[str]]:
    """A module that has just run, as an entry."""
    ns = module.__dict__
    if callable(ns.get("__getattr__")):
        raise Uncacheable("it has a module __getattr__ of its own")
    file = getattr(module, "__file__", None)
    source = Path(file).read_text() if file else ""
    tree = ast.parse(source)
    defs = _top_defs(tree)
    enc = Encoder(set(model_modules) - {name}, name)
    # Libraries the source imports from: `from build123d import *` binds
    # names that are best kept as "build123d's", whatever they are.
    libraries = [m for m in _imported_modules(tree)
                 if m not in model_modules and m != name and m in sys.modules]
    names: list = []          # [name, encoded] in module order
    lazy: dict = {}           # name -> ["module", m] | ["ref", m, q]: imported on first use
    redefine: dict = {}       # name -> line of its def/class
    unkept: list[str] = []
    why: dict[str, str] = {}
    for k, v in list(ns.items()):
        if k in _SKIP_DUNDER:
            continue
        dunder = k.startswith("__") and k.endswith("__")
        if dunder and k not in _KEEP_DUNDER:
            continue
        # This model's own functions and classes: defined again from source.
        if isinstance(v, (types.FunctionType, type)) and getattr(v, "__module__", None) == name \
                and getattr(v, "__qualname__", None) == k:
            node = _matching_def(defs.get(k) or [], v, file)
            # A function that has had attributes set on it is more than its def.
            if node is not None and not (isinstance(v, types.FunctionType) and v.__dict__):
                redefine[k] = node.lineno
            else:
                unkept.append(k)
                why[k] = "not made by a plain top-level def/class"
            continue
        # Another model, or something of one: imported when first used.
        if isinstance(v, types.ModuleType) and v.__name__ in model_modules and v.__name__ != name:
            lazy[k] = ["module", v.__name__]
            continue
        if isinstance(v, (types.FunctionType, type)) and getattr(v, "__module__", None) in model_modules \
                and getattr(v, "__module__", None) != name and getattr(v, "__qualname__", "") \
                and "." not in v.__qualname__ and "<" not in v.__qualname__:
            lazy[k] = ["ref", v.__module__, v.__qualname__]
            continue
        if not dunder and type(v) not in (bool, int, float, str, type(None)):
            lib = next((m for m in libraries if getattr(sys.modules[m], k, _NOTHING) is v), None)
            if lib is not None:
                names.append([k, {"ref": [lib, k]}])
                continue
        mark = enc.mark()
        try:
            names.append([k, enc.enc(v)])
        except Exception as exc:                        # noqa: BLE001 - not kept, never fatal
            enc.rollback(mark)
            if not dunder:
                unkept.append(k)
                why[k] = str(exc)[:200] or type(exc).__name__
    # A function or class is defined again from its source, reading this
    # module's names when it runs. One that reads a name that is not kept
    # would fail where the original worked: it is not kept either, until
    # nothing changes.
    reads = _reads(source, file, {k: next(n for n in defs[k] if n.lineno == line)
                                  for k, line in redefine.items()})
    defaults: dict = {}
    for k in list(redefine):
        v = ns[k]
        if isinstance(v, types.FunctionType) and (v.__defaults__ or v.__kwdefaults__):
            # Defaults as they were when the def ran, not as the names are now.
            mark = enc.mark()
            try:
                defaults[k] = [enc.enc(v.__defaults__), enc.enc(v.__kwdefaults__)]
            except Exception as exc:                    # noqa: BLE001
                enc.rollback(mark)
                redefine.pop(k)
                unkept.append(k)
                why[k] = f"defaults: {exc}"[:200]
    while True:
        bad = set(unkept)
        drop = [k for k in redefine if reads[k] & bad]
        if not drop:
            break
        for k in drop:
            redefine.pop(k)
            defaults.pop(k, None)
            unkept.append(k)
            why[k] = "reads " + ", ".join(sorted(reads[k] & bad)[:4])
    # Other models those functions read: imported with this one, not later.
    needed = set().union(*(reads[k] for k in redefine)) if redefine else set()
    eager = sorted(k for k in lazy if k in needed)
    meta = {"names": names, "objects": enc.objects, "lazy": lazy, "eager": eager, "why": why,
            "redefine": redefine, "defaults": defaults, "all": sorted(k for k in ns if not k.startswith("__")) +
            [k for k in ns if k in _KEEP_DUNDER],
            "future": [n.lineno for n in tree.body
                       if isinstance(n, ast.ImportFrom) and n.module == "__future__"]}
    return meta, enc, sorted(set(unkept))


_NOTHING = object()


def _imported_modules(tree: ast.Module) -> list[str]:
    """`from x.y import ...` and `import x.y` at the top of a source, in order."""
    out = []
    for node in tree.body:
        if isinstance(node, ast.ImportFrom) and not node.level and node.module:
            out.append(node.module)
        elif isinstance(node, ast.Import):
            out += [a.name for a in node.names]
    return list(dict.fromkeys(out))


def _matching_def(nodes: list, v, file) -> ast.AST | None:
    """The def/class statement that made `v` - the last one by that name
    is not always it."""
    if isinstance(v, types.FunctionType):
        code = v.__code__
        if code.co_filename != file:
            return None
        for n in nodes:
            first = min([n.lineno, *[d.lineno for d in getattr(n, "decorator_list", [])]])
            if code.co_firstlineno in (n.lineno, first) and not isinstance(n, ast.ClassDef):
                if getattr(n, "decorator_list", None):
                    return None     # a decorated function may not be what the def made
                return n
        return None
    classes = [n for n in nodes if isinstance(n, ast.ClassDef)]
    return classes[0] if len(classes) == 1 and len(nodes) == 1 else None


def _fill(module, meta: dict, shapes: Path, loader: _Loader, cache: Cache) -> None:
    """An entry into a module that is being imported."""
    ns = module.__dict__
    name = module.__name__
    # What it printed, unless that was said already in this process.
    if name not in _REPLAYED:
        _replay(meta.get("out") or [], cache)
        _REPLAYED.add(name)
    for k, v in (meta.get("env") or {}).items():
        _set_env(k, v)
    dec = Decoder(meta["objects"], shapes if shapes.exists() else None)
    for k, e in meta["names"]:
        ns[k] = dec.dec(e)
    lazy = dict(meta.get("lazy") or {})
    for k in meta.get("eager") or []:
        ns[k] = _lazy_value(lazy.pop(k))
    if meta.get("redefine"):
        source = Path(module.__file__).read_text()
        tree = ast.parse(source)
        lines = set(meta["redefine"].values()) | set(meta.get("future") or [])
        body = [n for n in tree.body if getattr(n, "lineno", None) in lines and (
            isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
            or isinstance(n, ast.ImportFrom) and n.module == "__future__")]
        code = compile(ast.Module(body=body, type_ignores=[]), module.__file__, "exec",
                       dont_inherit=True)
        exec(code, ns)                                  # noqa: S102 - the model's own defs
        for k, (pos, kw) in (meta.get("defaults") or {}).items():
            ns[k].__defaults__ = dec.dec(pos)
            ns[k].__kwdefaults__ = dec.dec(kw)
    unkept = set(meta.get("unkept") or [])
    known = set(meta.get("all") or [])

    def __getattr__(attr):
        if attr in lazy:
            value = _lazy_value(lazy.pop(attr))
            ns[attr] = value
            return value
        if attr in unkept or attr in known:
            # Not kept (or, unforeseen, kept but not restored): the source
            # runs after all, in this module, and answers.
            ns.pop("__getattr__", None)
            loader.run_source(module)
            if attr in ns:
                return ns[attr]
        raise AttributeError(f"module {name!r} has no attribute {attr!r}")

    ns["__getattr__"] = __getattr__


def _lazy_value(spec: list):
    if spec[0] == "module":
        return importlib.import_module(spec[1])
    return getattr(importlib.import_module(spec[1]), spec[2])


def _replay(out: list, cache: Cache) -> None:
    for item in out:
        if isinstance(item, str):
            sys.stdout.write(item)
            continue
        _kind, name, vkey = item
        if name in sys.modules or name in _REPLAYED:
            continue
        got = cache.store.read("m", vkey)
        if got:
            _REPLAYED.add(name)
            _replay(got[0].get("out") or [], cache)


# ---------------------------------------------------------------- STEP files

def wrap_import_step(store: Store, stats: dict | None = None) -> None:
    """build123d.import_step reads a large file once per content: after
    that, the same Compound - children, labels and colours - from BREP."""
    import build123d
    import build123d.importers as importers
    original = getattr(importers.import_step, "__redline_original__", importers.import_step)
    stats = stats if stats is not None else {}

    def import_step(filename, *args, **kwargs):
        try:
            path = Path(os.fsdecode(filename))
            big = path.stat().st_size >= STEP_MIN
        except (OSError, TypeError):
            big = False
        if not big:
            return original(filename, *args, **kwargs)
        key = _sha(json.dumps([runtime(), "import_step", _file_sha(path), repr(args),
                               repr(sorted(kwargs.items()))]))
        for attempt in (1, 2):
            got = store.read("step", key)
            if got:
                try:
                    meta, shapes = got
                    value = Decoder(meta["objects"], shapes).dec(meta["value"])
                    stats["step_hit"] = stats.get("step_hit", 0) + 1
                    _debug(f"STEP {path.name}: from the cache")
                    return value
                except Exception as exc:                # noqa: BLE001
                    _debug(f"STEP {path.name}: entry unreadable ({exc})")
                    shutil.rmtree(store.path("step", key), ignore_errors=True)
            if attempt == 2:
                break
            with store.lock("step", key):
                if store.has("step", key):
                    continue
                value = original(filename, *args, **kwargs)
                stats["step_miss"] = stats.get("step_miss", 0) + 1
                try:
                    meta, enc = encode_value(value)
                    store.write("step", key, meta, enc)
                except Exception as exc:                # noqa: BLE001 - kept or not, it is read
                    _debug(f"STEP {path.name}: not kept ({type(exc).__name__}: {exc})")
                return value
        return original(filename, *args, **kwargs)

    import_step.__redline_original__ = original
    import_step.__wrapped__ = original
    import_step.__doc__ = original.__doc__
    importers.import_step = import_step
    build123d.import_step = import_step


# ---------------------------------------------------------------- entry point

def install(models_dir: Path, root: Path | None = None, target: str | None = None) -> Cache | None:
    """Serve the build directory's models from the cache (export_model.py,
    before the model is loaded). None when the cache is off."""
    where = directory()
    if where is None:
        return None
    models_dir = Path(models_dir)
    root = Path(root) if root else models_dir.parent
    store = Store(where)
    cache = Cache(models_dir, root, store, target)
    try:
        cache.scan()
    except Exception as exc:                            # noqa: BLE001 - build as before
        _debug(f"not used: {type(exc).__name__}: {exc}")
        return None
    if not isinstance(sys.stdout, _Tee):
        sys.stdout = _Tee(sys.stdout)
    if not isinstance(sys.stderr, _Tee):
        sys.stderr = _Tee(sys.stderr)
    sys.meta_path.insert(0, cache)
    cache.wrap_steps = lambda: wrap_import_step(store, cache.stats)
    try:
        cache.wrap_steps()
    except Exception as exc:                            # noqa: BLE001
        _debug(f"STEP cache not used: {exc}")
    return cache


def finish(cache: Cache | None, report: Path | None = None) -> None:
    """After the build: what the cache did - into `report` (JSON, next to
    the viewer payload, for the build to pass on) and, with DEBUG, stderr -
    and the cache kept within its size."""
    if cache is None:
        return
    _debug(json.dumps(cache.stats))
    if report is not None:
        try:
            Path(report).write_text(json.dumps(cache.stats))
        except OSError:
            pass
    try:
        cache.store.prune(_size(os.environ.get("REDLINE_BUILD_CACHE_MAX", "4G")))
    except Exception:                                   # noqa: BLE001
        pass
